name: davaistore_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  go_router: ^16.2.1
  salomon_bottom_bar: ^3.3.2
  dio: ^5.9.0
  awesome_dio_interceptor: ^1.3.0
  shared_preferences: ^2.5.3
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.1.0
  http: ^1.5.0
  build_runner: ^2.5.4
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.7.1
  retrofit: ^4.7.2
  retrofit_generator: 9.7.0
  image_picker: ^1.2.0
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design:
    true

    # - assets/images/
